### PR TITLE
Add test for polygon with hole

### PR DESCRIPTION
**Pull request by Joxit**
New test case : polygon with hole

It fails and this is very odd...

```
shapefile-rs
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 00 00 27 0a 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00'_0000┊00000000│
│00000010│ 00 00 00 00 00 00 00 00 ┊ 00 00 00 a0 e8 03 00 00 │00000000┊000××•00│
│00000020│ 05 00 00 00 00 00 00 00 ┊ 00 00 5e c0 00 00 00 00 │•0000000┊00^×0000│
│00000030│ 00 00 4e c0 00 00 00 00 ┊ 00 00 5e 40 00 00 00 00 │00N×0000┊00^@0000│
│00000040│ 00 00 4e 40 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00N@0000┊00000000│
│00000050│ 00 00 00 00 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00000000┊00000000│
│00000060│ 00 00 00 00 00 00 00 01 ┊ 00 00 00 6a 05 00 00 00 │0000000•┊000j•000│
│00000070│ 00 00 00 00 00 00 5e c0 ┊ 00 00 00 00 00 00 4e c0 │000000^×┊000000N×│
│00000080│ 00 00 00 00 00 00 5e 40 ┊ 00 00 00 00 00 00 4e 40 │000000^@┊000000N@│
│00000090│ 02 00 00 00 0a 00 00 00 ┊ 00 00 00 00 05 00 00 00 │•000_000┊0000•000│
│000000a0│ 00 00 00 00 00 00 5e c0 ┊ 00 00 00 00 00 00 4e 40 │000000^×┊000000N@│
│000000b0│ 00 00 00 00 00 00 5e 40 ┊ 00 00 00 00 00 00 4e 40 │000000^@┊000000N@│
│000000c0│ 00 00 00 00 00 00 5e 40 ┊ 00 00 00 00 00 00 4e c0 │000000^@┊000000N×│
│000000d0│ 00 00 00 00 00 00 5e c0 ┊ 00 00 00 00 00 00 4e c0 │000000^×┊000000N×│
│000000e0│ 00 00 00 00 00 00 5e c0 ┊ 00 00 00 00 00 00 4e 40 │000000^×┊000000N@│
│000000f0│ 00 00 00 00 00 00 4e c0 ┊ 00 00 00 00 00 00 3e 40 │000000N×┊000000>@│
│00000100│ 00 00 00 00 00 00 4e 40 ┊ 00 00 00 00 00 00 3e 40 │000000N@┊000000>@│
│00000110│ 00 00 00 00 00 00 4e 40 ┊ 00 00 00 00 00 00 3e c0 │000000N@┊000000>×│
│00000120│ 00 00 00 00 00 00 4e c0 ┊ 00 00 00 00 00 00 3e c0 │000000N×┊000000>×│
│00000130│ 00 00 00 00 00 00 4e c0 ┊ 00 00 00 00 00 00 3e 40 │000000N×┊000000>@│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
expected:
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 00 00 27 0a 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00'_0000┊00000000│
│00000010│ 00 00 00 00 00 00 00 00 ┊ 00 00 00 a0 e8 03 00 00 │00000000┊000××•00│
│00000020│ 05 00 00 00 00 00 00 00 ┊ 00 00 5e c0 00 00 00 00 │•0000000┊00^×0000│
│00000030│ 00 00 4e c0 00 00 00 00 ┊ 00 00 5e 40 00 00 00 00 │00N×0000┊00^@0000│
│00000040│ 00 00 4e 40 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00N@0000┊00000000│
│00000050│ 00 00 00 00 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00000000┊00000000│
│00000060│ 00 00 00 00 00 00 00 01 ┊ 00 00 00 6a 05 00 00 00 │0000000•┊000j•000│
│00000070│ 00 00 00 00 00 00 5e c0 ┊ 00 00 00 00 00 00 4e c0 │000000^×┊000000N×│
│00000080│ 00 00 00 00 00 00 5e 40 ┊ 00 00 00 00 00 00 4e 40 │000000^@┊000000N@│
│00000090│ 02 00 00 00 0a 00 00 00 ┊ 00 00 00 00 05 00 00 00 │•000_000┊0000•000│
│000000a0│ 00 00 00 00 00 00 5e c0 ┊ 00 00 00 00 00 00 4e 40 │000000^×┊000000N@│
│000000b0│ 00 00 00 00 00 00 5e 40 ┊ 00 00 00 00 00 00 4e 40 │000000^@┊000000N@│
│000000c0│ 00 00 00 00 00 00 5e 40 ┊ 00 00 00 00 00 00 4e c0 │000000^@┊000000N×│
│000000d0│ 00 00 00 00 00 00 5e c0 ┊ 00 00 00 00 00 00 4e c0 │000000^×┊000000N×│
│000000e0│ 00 00 00 00 00 00 5e c0 ┊ 00 00 00 00 00 00 4e 40 │000000^×┊000000N@│
│000000f0│ 00 00 00 00 00 00 4e c0 ┊ 00 00 00 00 00 00 3e 40 │000000N×┊000000>@│
│00000100│ 00 00 00 00 00 00 4e c0 ┊ 00 00 00 00 00 00 3e c0 │000000N×┊000000>×│
│00000110│ 00 00 00 00 00 00 4e 40 ┊ 00 00 00 00 00 00 3e c0 │000000N@┊000000>×│
│00000120│ 00 00 00 00 00 00 4e 40 ┊ 00 00 00 00 00 00 3e 40 │000000N@┊000000>@│
│00000130│ 00 00 00 00 00 00 4e c0 ┊ 00 00 00 00 00 00 3e 40 │000000N×┊000000>@│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

The failure starts at the line `00000100`

I did some debug in `record::io::write_points` something like 

```rust
        let mut vec : Vec<u8>= vec![];
        vec.write_f64::<LittleEndian>(point.x())?;
        vec.write_f64::<LittleEndian>(point.y())?;
        println!("{:?} {:?}, {:?}", point.x(), point.y(), vec);
```

And the output was:
```
120.0 60.0, [0, 0, 0, 0, 0, 0, 94, 64, 0, 0, 0, 0, 0, 0, 78, 64]
120.0 -60.0, [0, 0, 0, 0, 0, 0, 94, 64, 0, 0, 0, 0, 0, 0, 78, 192]
-120.0 -60.0, [0, 0, 0, 0, 0, 0, 94, 192, 0, 0, 0, 0, 0, 0, 78, 192]
-120.0 60.0, [0, 0, 0, 0, 0, 0, 94, 192, 0, 0, 0, 0, 0, 0, 78, 64]
-60.0 30.0, [0, 0, 0, 0, 0, 0, 78, 192, 0, 0, 0, 0, 0, 0, 62, 64]
60.0 30.0, [0, 0, 0, 0, 0, 0, 78, 64, 0, 0, 0, 0, 0, 0, 62, 64]
60.0 -30.0, [0, 0, 0, 0, 0, 0, 78, 64, 0, 0, 0, 0, 0, 0, 62, 192]
-60.0 -30.0, [0, 0, 0, 0, 0, 0, 78, 192, 0, 0, 0, 0, 0, 0, 62, 192]
-60.0 30.0, [0, 0, 0, 0, 0, 0, 78, 192, 0, 0, 0, 0, 0, 0, 62, 64]
```

The raw data was : 
```geojson
{
  "type": "Polygon",
  "coordinates": [
    [
      [ -120, 60 ],
      [ 120, 60 ],
      [ 120, -60 ],
      [ -120, -60 ],
      [ -120, 60 ]
    ],
    [
      [ -60, 30 ],
      [ 60, 30 ],
      [ 60, -30 ],
      [ -60, -30 ],
      [ -60, 30 ]
    ]
  ]
}
```

Values are in the right order, but the write_f64 seems to be broken somewhere...
`78 =>  0x4e`; `64 => 0x40`; `192 => 0xc0`; `62 => 0x3e`

### CODE REVIEW

**Comment by tmontaigu** [comment]
I don't think this can be considered a bug,

The problem here is that the `polygon_hole.shp` contains 2 rings, the first one is considered to be an *outer ring* the  second one is an *inner ring* (this gives a polygon with a hole).

In shapefiles the order of vertices is what is used to tell if the ring an *outer* or *inner* one.

From the esri shapefile pdf (page 12/34 in pdf viewer)
>  The order of vertices or orientation for a ring indicates which side of the ring is the interior of the polygon.[...]  Vertices of rings defining holes in polygons are in a counterclockwise direction.  Vertices for a single, ringed polygon are, therefore, always in clockwise order. 

In the test, the created polygon has 2 rings, and for these 2 rings the vertices order is clockwise, thus they are considered as *outer rings*. If we reverse the order of the second part of then the test passes.

The standard says 
>  A polygon may contain multiple outer rings.

So I would not consider it a bug. However we do have a problem in the fact that the user has currently no way to specify if the ring should be considered as an *outer ring* or *inner ring* so that points are properly ordered in the resulting file unless he knows that fact and orders point by himself.

**Comment by Joxit** [comment]
Oh yes you're right, I'm truly sorry, my polygon was wrong, I've [updated](https://github.com/tmontaigu/shapefile-rs/compare/798d36a372e3f7082af84ab068b91bc9d3960c83..fa922e4be63fb3fb1dd192861021d6dd84f4e7be) it. I've forgotten to reverse points from the GeoJSON for the inner polygon.

The test purpose was to check if we can generate polygon with hole. So I take a GeoJSON, I used ogr2ogr to transform the GeoJson into a Shapefile and then I checked if shapefile-rs was OK with that. That means the Shapefile was correct but the test wasn't.

Now I've reversed the points order from my test, but the test is still failing.
I found that, in fact shapefile-rs is reversing every first hole.

https://github.com/tmontaigu/shapefile-rs/blob/49b81c0dc6a42177f147f2c145a2eb713d0e7e13/src/record/poly.rs#L565-L568

In my test,
1. the first part is a outer and has_outer_ring = false
2. the second part is an inner and has_outer_ring = false; so we enter in the condition and reverses points; then has_outer_ring = true and we never enter in this condition again.

I think this part should be done only on `parts_points[0]` because as you said, we can't know if the user is adding a inner or not.

**Comment by tmontaigu** [comment]
I forgot to say I need do add 
```Rust
if super::ring_type_from_points_ordering(&points) == super::RingType::InnerRing && !has_outer_ring { 
//...
 }  else {
    has_outer_ring = true;
}
```

I'm planning to change the Polygons and multipatch shapes to be something like
```Rust
struct Polygon {
   parts: Vec<PolygonRing>
}

// With

enum PolygonRing {
    Outter(Vec<Point>),
    Inner(Vec<Point>),
}


// OR (I don't know yet which way would be the best)
struct PolygonRing {
    points: Vec<Point>,
    ring_type: RingType
}

enum RingType {
    Outer,
    Inner
}
```

With this, when reading a polygon from a shapefile it will be easy to know the meaning of the ring 
and now we have a way for the user to specify the type for the rings of the polygons so we can order the points accordingly

**Comment by Joxit** [comment]
You're right, it works now :) thanks ! I added your fix to my commit !

Maybe enum is cool, just like geo_types did with `Geometry`. Furthermore, you can do something like to get points
```rust
enum PolygonRing {
    Outer(Vec<Point>),
    Inner(Vec<Point>),
}

impl PolygonRing {
    fn points(&self) -> &Vec<Point> {
        match self {
            PolygonRing::Outer(points) => points,
            PolygonRing::Inner(points) => points,
        }
    }
}
```

But with struct, you can reverse the points order at creation...
```rust
struct PolygonRing {
    points: Vec<Point>,
    ring_type: RingType
}

enum RingType {
    Outer,
    Inner
}

impl PolygonRing {
    fn new(points: Vec<Point>, ring_type: RingType) -> Self {
        match ring_type {
            RingType::Outer => {
                if ring_type_from_points_ordering(&points) == super::RingType::InnerRing {
                    points.reverse();
                }
            }
            RingType::Inner => {
                if ring_type_from_points_ordering(&points) == super::RingType::OuterRing {
                    points.reverse();
                }
            }
        }
        Self {
            points,
            ring_type
        }
    }
}
```

Hard to decide :thinking:

**Comment by tmontaigu** [comment]
Yes, I think iIwould find the version with the enum-only a bit cooler but the fact that you can’t reorder points when creating the ring makes it less appealing

**Pull request merged**
